name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

# Use the same profile as local (your [profile.default] has via_ir = true)
env:
  FOUNDRY_PROFILE: default

jobs:
  check:
    name: Foundry project
    # Pin the runner to avoid ubuntu-latest drift (24.04). 22.04 is stable on Actions.
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show runner OS
        run: |
          cat /etc/os-release
          uname -a

      - name: Install Foundry (stable)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Foundry versions & config
        run: |
          forge --version
          forge config
          svm which 0.8.28 || true

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build (pin solc exactly)
        run: |
          forge clean
          forge build --sizes --use 0.8.28 --no-auto-detect
        id: build

      - name: Run selector clash check
        run: |
          chmod +x script/check-selectors.sh
          script/check-selectors.sh
        id: selectorClash

      - name: Run Forge tests (pin solc exactly)
        run: forge test -vvv --use 0.8.28 --no-auto-detect
        id: test
