name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default
  # OPTIONAL: set this to your local forge commit to be 100% identical.
  # Find it with: `forge --version` (it prints a commit hash).
  FOUNDRY_COMMIT: "v1.4.0"  # or a commit like "e8aac2f"

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Prepare apt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates curl git build-essential pkg-config libssl-dev \
            clang cmake llvm make unzip xz-utils python3 jq
          update-ca-certificates

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Build Foundry from source so it links to 20.04's glibc (2.31)
      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Build Foundry (forge/cast/anvil/chisel)
        run: |
          git clone https://github.com/foundry-rs/foundry.git
          cd foundry
          # Checkout your exact local version (tag or commit)
          git checkout "${FOUNDRY_COMMIT}"
          $HOME/.cargo/bin/cargo build --release --locked \
            -p forge -p cast -p anvil -p chisel
          echo "$PWD/target/release" >> "$GITHUB_PATH"

      - name: Show versions & config
        run: |
          cat /etc/os-release
          forge --version
          forge config

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build (pin solc exactly)
        run: |
          svm install 0.8.28
          forge clean
          forge build --sizes --use 0.8.28 --no-auto-detect
        id: build

      - name: Run selector clash check
        run: |
          chmod +x script/check-selectors.sh
          script/check-selectors.sh
        id: selectorClash

      - name: Run Forge tests (pin solc exactly)
        run: forge test -vvv --use 0.8.28 --no-auto-detect
        id: test
