name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

# Use your local profile (via_ir = true in [profile.default])
env:
  FOUNDRY_PROFILE: default

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest

    # <<< key part: run all steps inside Ubuntu 20.04 like your local machine
    container:
      image: ubuntu:20.04

    steps:
      - name: Prepare apt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates curl git python3 jq xz-utils
          update-ca-certificates

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry (stable, same as local)
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.foundry/bin" >> "$GITHUB_PATH"
          ~/.foundry/bin/foundryup

      - name: Show versions & config
        run: |
          cat /etc/os-release
          forge --version
          forge config

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build (pin solc exactly)
        run: |
          svm install 0.8.28
          forge clean
          forge build --sizes --use 0.8.28 --no-auto-detect
        id: build

      - name: Run selector clash check
        run: |
          chmod +x script/check-selectors.sh
          script/check-selectors.sh
        id: selectorClash

      - name: Run Forge tests (pin solc exactly)
        run: forge test -vvv --use 0.8.28 --no-auto-detect
        id: test
